-- MySQL Script generated by MySQL Workbench
-- Tue Jul  3 00:24:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL,
  `nombre_cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Oficina` (
  `idOficina` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idOficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre_per` VARCHAR(50) NULL,
  `apellido_per` VARCHAR(50) NULL,
  `dni_per` VARCHAR(50) NULL,
  `Cargo_idCargo` INT NOT NULL,
  `Oficina_idOficina` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Cargo1_idx` (`Cargo_idCargo` ASC),
  INDEX `fk_Persona_Oficina1_idx` (`Oficina_idOficina` ASC),
  CONSTRAINT `fk_Persona_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Oficina1`
    FOREIGN KEY (`Oficina_idOficina`)
    REFERENCES `mydb`.`Oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_doc` (
  `idTipo_doc` INT NOT NULL,
  `nombre_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documento` (
  `idDocumento` INT NOT NULL AUTO_INCREMENT,
  `Persona_idemisor` INT NOT NULL,
  `Persona_idremitente` INT NOT NULL,
  `nombre_doc` VARCHAR(150) NULL,
  `Documentocol` VARCHAR(45) NULL,
  `fecha_recibido` DATE NULL,
  `Tipo_doc_idTipo_doc` INT NOT NULL,
  `detalle_doc` VARCHAR(200) NULL,
  `img_doc` BLOB NULL,
  `fecha_emision` DATE NULL,
  `ubicacion` VARCHAR(60) NULL,
  INDEX `fk_Persona_has_Persona_Persona1_idx` (`Persona_idremitente` ASC),
  INDEX `fk_Persona_has_Persona_Persona_idx` (`Persona_idemisor` ASC),
  PRIMARY KEY (`idDocumento`),
  INDEX `fk_Documento_Tipo_doc1_idx` (`Tipo_doc_idTipo_doc` ASC),
  CONSTRAINT `fk_Persona_has_Persona_Persona`
    FOREIGN KEY (`Persona_idemisor`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Persona_Persona1`
    FOREIGN KEY (`Persona_idremitente`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documento_Tipo_doc1`
    FOREIGN KEY (`Tipo_doc_idTipo_doc`)
    REFERENCES `mydb`.`Tipo_doc` (`idTipo_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `idRoles` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `Roles_idRoles` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_user_Roles1_idx` (`Roles_idRoles` ASC),
  CONSTRAINT `fk_user_Roles1`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `mydb`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial_de_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historial_de_ingreso` (
  `Documento_idDocumento` INT NOT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`Documento_idDocumento`, `user_idUser`),
  INDEX `fk_Documento_has_user_user1_idx` (`user_idUser` ASC),
  INDEX `fk_Documento_has_user_Documento1_idx` (`Documento_idDocumento` ASC),
  CONSTRAINT `fk_Documento_has_user_Documento1`
    FOREIGN KEY (`Documento_idDocumento`)
    REFERENCES `mydb`.`Documento` (`idDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documento_has_user_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unidad` (
  `idUnidad` INT NOT NULL,
  `nombre_unidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idUnidad`),
  CONSTRAINT `fk_Unidad_Oficina1`
    FOREIGN KEY (`idUnidad`)
    REFERENCES `mydb`.`Oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `nombre_departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartamento`),
  CONSTRAINT `fk_Departamento_Oficina1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`Oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seguimiento` (
  `Oficina_idOficina` INT NOT NULL,
  `Documento_idDocumento` INT NOT NULL,
  `visto_recibido` TINYINT(1) NULL,
  `idSeguimiento` VARCHAR(45) BINARY NOT NULL,
  INDEX `fk_Oficina_has_Documento_Documento1_idx` (`Documento_idDocumento` ASC),
  INDEX `fk_Oficina_has_Documento_Oficina1_idx` (`Oficina_idOficina` ASC),
  PRIMARY KEY (`idSeguimiento`),
  CONSTRAINT `fk_Oficina_has_Documento_Oficina1`
    FOREIGN KEY (`Oficina_idOficina`)
    REFERENCES `mydb`.`Oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oficina_has_Documento_Documento1`
    FOREIGN KEY (`Documento_idDocumento`)
    REFERENCES `mydb`.`Documento` (`idDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
